# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Docunext
description: > # this means to ignore newlines until "baseurl:"
    Docunext Technology Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://docunext.com" # the base hostname & protocol for your site
github_username:  docunext

# Build settings
markdown: kramdown
exclude: [ content, _site ]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
